appointment/urls.py
from django.urls import path
from django.conf.urls import handler404
from django.contrib.flatpages import views as flat_views
from django_filters.views import FilterView
from . import views
from .views import (AptmtDetailView,
                    AptmtCreateView,
                    AptmtUpdateByUserView,
                    AptmtDeleteView,
                    MyAptmtListView,
                    AptmtCancelByUserView,
                    AllAptmtListView,
                    AptmtUpdateByAdminView,
                    MedRecordUpdateByDoctorView,
                    DoctorAptmtListView,
                    ClinicListView,
                    DoctorListView,
                    DoctorDetailView,
                    AptmtCompeteByDoctorView,
                    SiteSettingUpdateView,
                    AllDoctorScheduleListView,
                    DocScheduleCreateByAdminView,
                    DocScheduleUpdateByAdminView,
                    MyScheduleListView,
                    DocScheduleCreateByDoctorView,
                    DocScheduleUpdateByDoctorView,
                    DocScheduleDeleteView,
                    FlatTextPageUpdateView,
                    ClinicUpdateView,
                    ClinicCreateView,
                    ClinicDeleteView,
                    ClinicDetailView,
                    AllAptmtCalendarView,
                    MyAptmtCalendarView,
                    DoctorAptmtCalendarView,
                  )

urlpatterns = [
    path('', views.home, name='home'),
    path('site-settings/<int:scope>/', SiteSettingUpdateView.as_view(), name='site-settings'),
    path('appointment/all/', AllAptmtListView.as_view(), name='aptmts-all'),
    path('appointment/all/calendar/', AllAptmtCalendarView.as_view(), name='aptmts-all-calendar'),
    path('appointment/my-appointments/', MyAptmtListView.as_view(), name='my-aptmts'),
    path('appointment/my-appointments/calendar/', MyAptmtCalendarView.as_view(), name='my-aptmts-calendar'),
    path('appointment/doc-appointments/', DoctorAptmtListView.as_view(), name='doc-aptmts'),
    path('appointment/doc-appointments/calendar/', DoctorAptmtCalendarView.as_view(), name='doc-aptmts-calendar'),
    path('appointment/<int:pk>/', AptmtDetailView.as_view(), name='aptmt-detail'),
    path('appointment/<int:pk>/delete/', AptmtDeleteView.as_view(), name='aptmt-delete'),
    path('appointment/<int:pk>/cancel-by-user/', AptmtCancelByUserView.as_view(), name='aptmt-cancel-by-user'),
    path('appointment/<int:pk>/complete/', AptmtCompeteByDoctorView.as_view(), name='aptmt-complete-by-doctor'),
    path('appointment/new/', AptmtCreateView.as_view(), name='aptmt-create'),
    path('appointment/check-profile-completeness/', views.check_profile_complete, name='check-profile-completeness'),
    path('appointment/<int:pk>/update/', AptmtUpdateByUserView.as_view(), name='aptmt-update-by-user'),
    path('appointment/<int:pk>/update-by-admin/', AptmtUpdateByAdminView.as_view(), name='aptmt-update-by-admin'),
    path('appointment/<int:appointment_id>/update-by-doctor/', MedRecordUpdateByDoctorView.as_view(),
         name='med-record-update-by-doctor'),
    # path('doctor-schedule/all/', AllDoctorScheduleListView.as_view(), name='doc-schedules-all'),
    # path('doctor-schedule/new/', DocScheduleCreateByAdminView.as_view(), name='doc-schedule-create-by-admin'),
    # path('doctor-schedule/<int:pk>/update/', DocScheduleUpdateByAdminView.as_view(),
    #      name='doc-schedule-update-by-admin'),
    # path('doctor-schedule/my/', MyScheduleListView.as_view(), name='my-schedule'),
    # path('doctor-schedule/my/new/', DocScheduleCreateByDoctorView.as_view(),
    #      name='doc-schedule-create-by-doctor'),
    # path('doctor-schedule/my/<int:pk>/update/', DocScheduleUpdateByDoctorView.as_view(),
    #      name='doc-schedule-update-by-doctor'),
    # path('doctor-schedule/<int:pk>/delete/', DocScheduleDeleteView.as_view(), name='doc-schedule-delete'),
    path('clinic/<int:pk>/update/', ClinicUpdateView.as_view(), name='clinic-update'),
    path('clinic/create/', ClinicCreateView.as_view(), name='clinic-create'),
    path('clinic/<int:pk>/delete/', ClinicDeleteView.as_view(), name='clinic-delete'),
    path('clinic-info/<int:pk>/', ClinicDetailView.as_view(), name='clinic-detail'),
    path('about/', flat_views.flatpage, {'url': '/about/'}, name='about'),
    path('contact-us/', flat_views.flatpage, {'url': '/contact-us/'}, name='contact-us'),
    path('terms-of-services/', flat_views.flatpage, {'url': '/terms-of-services/'}, name='terms-of-services'),
    path('privacy-policy/', flat_views.flatpage, {'url': '/privacy-policy/'}, name='privacy-policy'),
    path('flat-text-page/<int:pk>/update/', FlatTextPageUpdateView.as_view(), {'url': '/about-us/'},
         name='flat-text-page-update'),
    path('clinics/', ClinicListView.as_view(), name='clinics'),
    path('doctors/', DoctorListView.as_view(), name='doctors'),
    path('doctor/<int:pk>/', DoctorDetailView.as_view(), name='doctor-detail'),
    path('ajax/load-clinics/', views.load_clinics, name='ajax-load-clinics'),
]

# handler404 = views.error_404_view

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views as user_views

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('password-change', auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'),
         name='password_change'),
    path('password-change-done',
         auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
]

appointment/models.py
from django.db import models
from datetime import datetime
# import datetime
from django.urls import reverse
from users.models import User, DoctorSpeciality


class Status(models.Model):
    status = models.CharField(max_length=25)
    display = models.CharField(max_length=25, null=True)
    description = models.TextField(null=True)
    colour = models.CharField(max_length=6, null=True)

    def __str__(self):
        return self.display


class Clinic(models.Model):
    name = models.CharField(max_length=50)
    # contact_number = models.PositiveIntegerField(null=True)
    contact_number = models.CharField(max_length=50, null=True)
    email = models.EmailField(null=True)
    operating_time_from = models.TimeField(null=True)
    operating_time_to = models.TimeField(null=True)
    address = models.TextField(null=True)
    additional_info = models.TextField(null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('clinic-detail', kwargs={'pk': self.pk})


class Appointment(models.Model):
    appointment_number = models.CharField(max_length=50)
    patient = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='appointment_creator')
    status = models.ForeignKey(Status, default=1, on_delete=models.SET('Status Error'), null=True)
    speciality = models.ForeignKey(DoctorSpeciality, on_delete=models.SET_NULL, null=True,
                                   related_name='appointment_speciality')
    self_description = models.TextField(null=True)
    doctor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='appointment_doctor')
    preferred_doctor = models.CharField(max_length=50, null=True)
    clinic = models.ForeignKey(Clinic, on_delete=models.SET_NULL, null=True, related_name='appointment_clinic')
    appointment_datetime = models.DateTimeField()
    create_datetime = models.DateTimeField(default=datetime.now)
    last_updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                        related_name='appointment_update_by')
    last_updated_datetime = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f'{self.appointment_number}'

    def get_absolute_url(self):
        return reverse('aptmt-detail', kwargs={'pk': self.pk})

    @property
    def get_html_url(self):
        url = reverse('aptmt-detail', args=(self.id,))
        return f'{url}'


class MedicalRecord(models.Model):
    appointment = models.OneToOneField(Appointment, on_delete=models.CASCADE, related_name='medical_record')
    problems = models.TextField(null=True)
    medications = models.TextField(null=True)
    directives = models.TextField(null=True)
    allergies_and_adverse_reactions = models.TextField(null=True)
    last_updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                        related_name='medical_record_update_by')
    last_updated_datetime = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f'{self.appointment.appointment_number}'

    def get_absolute_url(self):
        return reverse('aptmt-detail', kwargs={'pk': self.appointment_id})


class DoctorSchedule(models.Model):
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='doctor')
    start_datetime = models.DateTimeField(default=datetime.now)
    end_datetime = models.DateTimeField(default=datetime.now)
    notes = models.TextField(null=True)
    create_datetime = models.DateTimeField(default=datetime.now)
    create_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='create_by')
    last_updated_datetime = models.DateTimeField(default=datetime.now)
    last_updated_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='update_by')


class SiteSetting(models.Model):
    aptmts_per_page = models.PositiveSmallIntegerField(default=10)
    patient_view_med_records = models.BooleanField(default=False)
    scope = models.PositiveSmallIntegerField(default=0, unique=True)
    doc_schedules_per_page = models.SmallIntegerField(default=10)

    def get_aptmts_per_page(self):
        return self.aptmts_per_page

    def get_doc_schedules_per_page(self):
        return self.doc_schedules_per_page

appointment/templates/appointment/about.html
{% extends "base.html" %}
{% block content %}
<h1>{{title}}</h1>
<div>

        {{ content }}

</div>
{% endblock content %}

appointment/templates/appointment/all_doc_schedule.html
{% extends "base.html" %}
{% block content %}
<!--<article class="media content-section">-->
    <div class="media-body">
        <div class="btn btn-primary btn-lg mt-1 mb-1">
            <a href="{% url 'doc-schedule-create-by-admin' %}">Add a Doctor Schedule</a>
        </div>
    </div><br>
<!--</article>-->
{% for docSchedule in docSchedules %}
{% include 'appointment/snippets/one_doctor_schedule.html' %}
{% endfor %}

{% if is_paginated %}

{% if page_obj.has_previous %}
<a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
<a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<!--<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>-->
<a class="btn btn-primary mb-4">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-primary mb-4" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
<a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}

{% endif %}
{% endblock content %}

appointment/templates/appointment/aptmt_cancel_by_user.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="" content-section>
    <form method="post" action="">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Appointment Cancel</legend>
            <h2>Are you sure you want to cancel this appointment?</h2>
            {{form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Yes, Cancel</button>
            <a class="btn btn-outline-secondary" href="{% url 'aptmt-detail' object.id %}">Back</a>
        </div>
    </form>
</div>
{% endblock content %}

appointment/templates/appointment/calendar.html
{% extends "base.html" %}
{% block content %}
{% include 'appointment/snippets/aptmt_status_legend.html' %}
{% include 'appointment/snippets/aptmt_view_switcher.html' %}
<article class="media content-section">
    <div class="media-body">
        <div class="cal-clearfix d-flex justify-content-between">
            <div>
                {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-outline-info align-self-center"
                   href="{% url 'aptmts-all-calendar' %}?{{ prev_month }}"> Previous Month </a>
                {% elif user.is_patient %}
                <a class="btn btn-outline-info align-self-center"
                   href="{% url 'my-aptmts-calendar' %}?{{ prev_month }}"> Previous Month </a>
                {% elif user.is_doctor and user.is_staff == 0 and user.is_superuser == 0 %}
                <a class="btn btn-outline-info align-self-center"
                   href="{% url 'doc-aptmts-calendar' %}?{{ prev_month }}"> Previous Month </a>
                {% endif %}
            </div>
            <div>

                {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-outline-info align-self-center" href="{% url 'aptmts-all-calendar' %}"> Current
                    Month </a>
                {% elif user.is_patient %}
                <a class="btn btn-outline-info align-self-center" href="{% url 'my-aptmts-calendar' %}"> Current
                    Month </a>
                {% elif user.is_doctor and user.is_staff == 0 and user.is_superuser == 0 %}
                <a class="btn btn-outline-info align-self-center" href="{% url 'doc-aptmts-calendar' %}"> Current
                    Month </a>
                {% endif %}

            </div>
            <div>
                {% if user.is_staff or user.is_superuser %}
                <a class="btn btn-outline-info align-self-center"
                   href="{% url 'aptmts-all-calendar' %}?{{ next_month }}"> Next Month </a>
                {% elif user.is_patient %}
                <a class="btn btn-outline-info align-self-center"
                   href="{% url 'my-aptmts-calendar' %}?{{ next_month }}"> Next Month </a>
                {% elif user.is_doctor and user.is_staff == 0 and user.is_superuser == 0 %}
                <a class="btn btn-outline-info align-self-center"
                   href="{% url 'doc-aptmts-calendar' %}?{{ next_month }}"> Next Month </a>
                {% endif %}

            </div>
        </div>
        {{ calendar }}
    </div>
</article>
{% endblock content %}

appointment/templates/appointment/clinic-create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<div class="" content-section>
    <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New Clinic</legend>
            {{form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
            <a class="btn btn-outline-secondary" href="{% url 'site-settings' 0 %}">Back</a>
        </div>
    </form>
</div>

{% endblock content %}

appointment/templates/appointment/clinic-detail.html
{% extends "base.html" %}
{% block content %}
<article class="media content-section">
    <div class="media-body">
        <legend class="border-bottom mb-4">{{clinic.name}}</legend>
        <div class="ml-2">
            <div class="d-flex flex-column mb-2">
                <div class="mr-2 font-weight-bold">Contact</div>
                {{ clinic.contact_number }}
            </div>
            <div class="d-flex flex-column mb-2">
                <div class="mr-2 font-weight-bold">Email</div>
                {{ clinic.email }}
            </div>

            <div class="d-flex flex-column mb-2">
                <div class="mr-2 font-weight-bold">Operating Time</div>
                <div>
                    From
                    <text class="font-weight-bold">{{ clinic.operating_time_from|time:'H:i' }}</text>
                    to
                    <text class="font-weight-bold">{{ clinic.operating_time_to|time:'H:i' }}</text>
                </div>

            </div>
            <div class="d-flex flex-column mb-2">
                <div class="mr-2 font-weight-bold">Address</div>
                {{ clinic.address }}
            </div>

            {% if clinic.additional_info %}
            <div class="d-flex flex-column mb-2">
                <div class="mr-2 font-weight-bold">Additional Information</div>
                <p>{{ clinic.additional_info }}</p>
            </div>
            {% endif %}

        </div>

    </div>
</article>
{% endblock content %}

appointment/templates/appointment/clinic-update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<div class="" content-section>
    <legend class="border-bottom mb-4">{{ object.name }} information update</legend>
    <form method="post" action="">
        {% csrf_token %}
        <fieldset class="form-group">
            {{form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
            <a class="btn btn-outline-secondary" href="{% url 'site-settings' 0 %}">Back</a>
        </div>
    </form>


</div>


{% endblock content %}

appointment/templates/appointment/clinics.html
{% extends "base.html" %}
{% block content %}
{% for clinic in clinics %}
<article class="media content-section">
    <div class="media-body ml-2">


        <div>
            <h2>{{ clinic.name }}</h2>
        </div>

        <div class="d-flex flex-column mb-2">
            <div>
                <text class="font-weight-bold">Contact Number:</text>
                {{ clinic.contact_number }}
            </div>

        </div>

        <div class="d-flex flex-column mb-2">
            <div>
                <text class="font-weight-bold">Email:</text>
                {{ clinic.email }}
            </div>

        </div>

        <div class="d-flex flex-column mb-2">
            <div>
                <text class="font-weight-bold">Operating Time:</text>

                From
                <text class="font-weight-bold">{{ clinic.operating_time_from|time:'H:i' }}</text>
                to
                <text class="font-weight-bold">{{ clinic.operating_time_to|time:'H:i' }}</text>
            </div>

        </div>

        <div class="d-flex flex-column mb-2">
            <div>
                <text class="font-weight-bold">Address:</text>
                {{ clinic.address }}
            </div>

        </div>
        <div>
            <a class="text-primary" href="{% url 'clinic-detail' clinic.id %}">Read more...</a>
        </div>


    </div>
</article>
{% endfor %}

{% if is_paginated %}

{% if page_obj.has_previous %}
<a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
<a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<!--<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>-->
<a class="btn btn-primary mb-4">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-primary mb-4" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
<a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}

{% endif %}
{% endblock content %}

appointment/templates/appointment/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<div class="content-section" >
    <form method="post" id="createAptmtForm" data-clinics-url="{% url 'ajax-load-clinics' %}">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">New Appointment</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
<script>
    $("#id_speciality").change(function () {
      var url = $("#createAptmtForm").attr("data-clinics-url");  // get the url of the `load_clinics` view
      var specialityId = $(this).val();  // get the selected speciality ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'speciality': specialityId       // add the speciality id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_clinic").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });



</script>

{% endblock content %}

appointment/templates/appointment/detail.html
{% extends "base.html" %}
{% block content %}

<article class="media content-section">

    <div class="media-body">
        <div class="d-flex flex-row">
            <legend class="border-bottom mb-4 align-self-center">Appointment Detail</legend>
            {% if user.is_staff or user.is_superuser %}
            <a class="btn btn-secondary btn-lg mt-1 mb-1 ml-auto align-self-center" href="{% url 'aptmts-all' %}">Back
                to List</a>
            {% elif user.is_doctor and user.is_staff == 0 and user.is_superuser == 0 %}
            <a class="btn btn-secondary btn-lg mt-1 mb-1 ml-auto align-self-center" href="{% url 'doc-aptmts' %}">Back
                to List</a>
            {% elif user.is_patient and user.is_staff == 0 and user.is_superuser == 0 %}
            <a class="btn btn-secondary btn-lg mt-1 mb-1 ml-auto align-self-center" href="{% url 'my-aptmts' %}">Back to
                List</a>
            {% endif %}
        </div>

        <div class="article-metadata">
            <div>
                <label>Current Status: </label>
                <label style="color:#{{object.status.colour}}">{{ object.status.display }}</label>
                <small class="text-muted float-right">Appointment request created at:
                    {{ object.create_datetime|date:'M d, Y f' }}</small>
            </div>


            {% if object.patient == user %}
            {% if object.status.id == 1 %}
            <div>
                <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'aptmt-update-by-user' object.id%}">Change</a>
                <a class="btn btn-warning btn-sm mt-1 mb-1" href="{% url 'aptmt-cancel-by-user' object.id%}">Cancel</a>
            </div>
            {% endif %}
            {% elif request.user.is_doctor and request.user.is_staff is False%}
            {% if object.status.id == 4 or object.status.id == 5 %}
            <div>
                <a class="btn btn-primary btn-sm mt-1 mb-1"
                   href="{% url 'med-record-update-by-doctor' object.id%}">Update</a>
                <a class="btn btn-success btn-sm mt-1 mb-1"
                   href="{% url 'aptmt-complete-by-doctor' object.id%}">Complete</a>
            </div>
            {% endif %}
            {% elif request.user.is_staff %}
            <div>

                <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'aptmt-update-by-admin' object.id%}">Update</a>

                {% if request.user.is_superuser %}
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'aptmt-delete' object.id%}">Delete</a>
                {% endif %}
            </div>
            {% endif %}
        </div>


        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-header" id="headingOne">
                    <h2 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne"
                                aria-expanded="true" aria-controls="collapseOne" data-parent="#accordionExample">
                            Patient Profile
                        </button>
                    </h2>
                </div>
                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne">
                    <div class="card-body">
                        {% include 'appointment\snippets\patient_profile.html' %}


                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h2 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"
                                data-parent="#accordionExample">
                            Appointment Information
                        </button>
                    </h2>
                </div>
                <div id="collapseTwo" class="collapse show" aria-labelledby="headingTwo">
                    <div class="card-body">
                        {% include 'appointment\snippets\aptmt_info.html' %}
                    </div>
                </div>
            </div>


            {% if request.user.is_doctor or request.user.is_staff %}
            <div class="card">
                <div class="card-header" id="headingThree">
                    <h2 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree"
                                data-parent="#accordionExample">
                            Medical Records
                        </button>
                    </h2>
                </div>
                <div id="collapseThree" class="collapse show" aria-labelledby="headingThree">
                    <div class="card-body">
                        {% include 'appointment/snippets/patient_medical_record.html' %}
                    </div>
                </div>
            </div>
            {% endif %}

            {% if request.user.is_patient and object.status.id == 6 and patient_view_med_records %}
            <div class="card">
                <div class="card-header" id="headingThree2">
                    <h2 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                data-target="#collapseThree2" aria-expanded="false" aria-controls="collapseThree2"
                                data-parent="#accordionExample">
                            Medical Records
                        </button>
                    </h2>
                </div>
                <div id="collapseThree2" class="collapse show" aria-labelledby="headingThree2">
                    <div class="card-body">
                        {% include 'appointment/snippets/patient_medical_record.html' %}
                    </div>
                </div>
            </div>
            {% endif %}

        </div>

    </div>
</article>
{% endblock content %}

appointment/templates/appointment/flat_text_page_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}
<div class="" content-section>
    <legend class="border-bottom mb-4">Edit: {{title}}</legend>

    <form method="post" action="">
        {% csrf_token %}
        <fieldset class="form-group">
            {{form|crispy}}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>

</div>
{% endblock content %}